#ifndef IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_CONVOLUTION_DEMO_HPP
#define IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_CONVOLUTION_DEMO_HPP


void convolve_demo ();


#endif /// IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_CONVOLUTION_DEMO_HPP.
