#ifndef IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_DELTA_FUNCTION_DEMO_HPP
#define IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_DELTA_FUNCTION_DEMO_HPP


void delta_function_demo ();


#endif /// IMAGE_CONVOLUTIONS_ALGORITHMS_DEMO_DELTA_FUNCTION_DEMO_HPP.
